version: "3.8"

services:
  db:
    image: postgres
    restart: always
    env_file:
      - ./server/.env
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8030:8080
    depends_on:
      - db
