version: '3.8'

services:
 db:
  image: postgres
  restart: always
  # networks:
  #  - default
  env_file:
   - ./server/.env
  ports:
   - 5432:5432
  volumes:
   - dbdata:/var/lib/postgresql/data

 adminer:
  image: adminer
  restart: always
  # networks:
  #  - default
  ports:
   - 8030:8080
  depends_on:
   - db

 server:
  build:
   context: ./server
   dockerfile: prod.Dockerfile
  restart: always
  # networks:
  #  - default
  ports:
   - 33433:33433
  volumes:
   - logs:/usr/src/app/logs
  depends_on:
   - adminer

volumes:
 dbdata:
  driver: local
 logs:
  driver: local
# networks:
#  default:
#   driver: bridge
