version: '3.1'

services:
 db:
  image: postgres
  restart: always
  environment:
   POSTGRES_PASSWORD: trytofindme
  ports:
   - 5432:5432

 adminer:
  image: adminer
  restart: always
  ports:
   - 8030:8080
  depends_on:
   - db

 server:
  build:
   context: ./server
   dockerfile: prod.Dockerfile
  restart: always
  ports:
   - 33433:33433
  depends_on:
   - adminer
