export const ADD_TEACHER = 'ADD_TEACHER';
export const REMOVE_TEACHER = 'REMOVE_TEACHER';
export const ADMIN_REQUEST = 'ADMIN_REQUEST';
// export const ADMIN_REQUEST_SUCCESS = 'ADMIN_REQUEST';
// export const ADMIN_REQUEST_FAILED = 'ADMIN_REQUEST';
