export const PUBLICK_REQUEST = 'PUBLICK_REQUEST';
export const PUBLICK_FAILED = 'PUBLICK_FAILED';
export const GET_ALL_STUFF = 'GET_ALL_STUFF';
export const GET_ONLY_TEACHER = 'GET_ONLY_TEACHER';
export const GET_ONLY_TEACHER_POSTS = 'GET_ONLY_TEACHER_POSTS';
