export const WHO_AM_I_REQUEST = 'WHO_AM_I_REQUEST';
export const WHO_AM_I_SUCCESS = 'WHO_AM_I_SUCCESS';
export const WHO_AM_I_FAILED = 'WHO_AM_I_FAILED';

export const POST_TEACHER_POSTS = 'POST_TEACHER_POSTS';
