export const WHO_AM_I_REQUEST = 'WHO_AM_I_REQUEST';
export const WHO_AM_I_SUCCESS = 'WHO_AM_I_SUCCESS';
export const WHO_AM_I_FAILED = 'WHO_AM_I_FAILED';

export const CLEAR_AUTH_DATA = 'CLEAR_AUTH_DATA';

export const POST_TEACHER_POSTS_REQUEST = 'POST_TEACHER_POSTS_REQUEST';
export const POST_TEACHER_POSTS_SUCCESS = 'POST_TEACHER_POSTS_SUCCESS';
export const POST_TEACHER_POSTS_FAILED = 'POST_TEACHER_POSTS_FAILED';
